### ISSUE TITLE
不太懂，这个attention在做什么

### ISSUE THREAD

**Issue by zhanghan1992** [IEIT-Yuan/Yuan2.0-M32#1]
![20240529-165548](https://github.com/IEIT-Yuan/Yuan2.0-M32/assets/40751364/a7a0b1f5-6eb2-42f9-ad33-ccc8312d6641)

**Comment by Zero-coder** [comment]
这篇文章逻辑感觉可以更严谨一点，E如果代表expert，那么attention router里面就有expert，图1里面的expert和attention router里面的expert到底是啥关系？这里的expert又是否一致？
