### ISSUE TITLE
llama-cpp-python推理时报错

### ISSUE THREAD

**Issue by linhao622** [IEIT-Yuan/Yuan2.0-M32#2]
使用llama-cpp-python推理时报错：unknown model architecture： ’yuan2_moe‘
llama-cpp-python版本：0.2.76
推理的模型：Yuan2-moe_0526_int4.gguf

**Comment by adonishong** [comment]
seems like no support from llama.cpp, looking forward to that ...

**Comment by Shawn-IEITSystems** [comment]
@zhaoxudong01 @Huifu1018

**Comment by Huifu1018** [comment]
> 使用llama-cpp-python推理时报错：unknown model architecture： ’yuan2_moe‘ llama-cpp-python版本：0.2.76 推理的模型：Yuan2-moe_0526_int4.gguf

我们提供已适配Yuan2.0模型的Llama.cpp项目，请参考 https://github.com/IEIT-Yuan/3rd_party

**Comment by Huifu1018** [comment]
> seems like no support from llama.cpp, looking forward to that ...

llama.cpp for Yuan2.0 LLMs, please refer to this project, https://github.com/IEIT-Yuan/3rd_party
